use serde_json::Value;
use crate::plugins::{PluginRegistry, escape_attr};

pub fn compile_to_html(tokens: &[Value], registry: &PluginRegistry) -> String {
    let mut html = String::new();

    for token in tokens {
        match token["type"].as_str().unwrap_or("") {
            "heading" => {
                let level = token["level"].as_u64().unwrap_or(1);
                let text = token["text"].as_str().unwrap_or("");
                // Normally we'd escape text, but let's assume inline HTML is allowed or generated by ast
                html.push_str(&format!("<h{}>{}</h{}>\n", level, text, level));
            }
            "paragraph" => {
                let text = token["text"].as_str().unwrap_or("");
                html.push_str(&format!("<p>{}</p>\n", text));
            }
            "plugin" => {
                let engine = token["engine"].as_str().unwrap_or("");
                if let Some(p) = registry.get(engine) {
                    if let Some(rendered) = p.render_html(token) {
                        html.push_str(&rendered);
                        html.push('\n');
                    }
                }
            }
            "code_block" => {
                let lang = token["language"].as_str().unwrap_or("");
                let code = token["code"].as_str().unwrap_or("");
                html.push_str(&format!("<pre><code class=\"language-{}\">{}</code></pre>\n", escape_attr(lang), escape_html(code)));
            }
            "hr" => {
                html.push_str("<hr />\n");
            }
            "list_item" => {
                let text = token["text"].as_str().unwrap_or("");
                html.push_str(&format!("<li>{}</li>\n", text));
            }
            "table" => {
                html.push_str("<table>\n<thead>\n<tr>\n");
                if let Some(headers) = token["headers"].as_array() {
                    for h in headers {
                        html.push_str(&format!("<th>{}</th>\n", h.as_str().unwrap_or("")));
                    }
                }
                html.push_str("</tr>\n</thead>\n<tbody>\n");
                if let Some(rows) = token["rows"].as_array() {
                    for row in rows {
                        html.push_str("<tr>\n");
                        if let Some(cells) = row.as_array() {
                            for cell in cells {
                                html.push_str(&format!("<td>{}</td>\n", cell.as_str().unwrap_or("")));
                            }
                        }
                        html.push_str("</tr>\n");
                    }
                }
                html.push_str("</tbody>\n</table>\n");
            }
            _ => {}
        }
    }

    html
}

fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&'  => out.push_str("&amp;"),
            '<'  => out.push_str("&lt;"),
            '>'  => out.push_str("&gt;"),
            '"'  => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _    => out.push(ch),
        }
    }
    out
}